site_name: dhis2 User Manual
docs_dir: 'src/commonmark/en/'

nav:
  - 'About': 'content/common/about-this-guide.md'
  - 'Getting Started': 'content/user/getting-started-help-to-navigate-the-user-guide.md'
  - 'What is DHIS2': 'content/user/what-is-dhis2.md'
  - 'Managing Dashboards': 'content/user/managing-dashboards.md'
  - 'Messaging': 'content/user/messaging.md'
  - 'Data Entry': 'content/user/using-the-data-entry-app.md'
  - 'Event Capture': 'content/user/using-the-event-capture-app.md'
  - 'Tracker Capture': 'content/user/using-the-tracker-capture-app.md'
  - 'Pivot Tables': 'content/user/analyze-data-in-pivot-tables.md'
  - 'Data Visualizer': 'content/user/using-the-data-visualizer-app.md'
  - 'GIS App': 'content/user/using-the-gis-app.md'
  - 'Maps App': 'content/user/using-the-maps-app.md'
  - 'Event Reports': 'content/user/using-the-event-reports-app.md'
  - 'Event Visualizer': 'content/user/using-the-event-visualizer-app.md'
  - 'Data Quality': 'content/user/control-data-quality.md'
  - 'Data Approval': 'content/user/data-approval.md'
  - 'Reports': 'content/user/using-reporting-functionality.md'
  - 'User Account': 'content/user/set-user-account-preferences.md'
  - 'Manage Users': 'content/user/manage-users-user-roles-and-user-groups.md'
  - 'Usage Analytics': 'content/user/visualize-usage-statistics.md'
  - 'Configure Metadata': 'content/user/configure-metadata.md'
  - 'Configure Programs in Maintenance': 'content/user/configure-programs-in-the-maintenance-app.md'
  - 'Configure Programs in Legacy App': 'content/user/configure-programs-in-the-programsattributes-app-legacy-app.md'
  - 'About Sharing of Objects': 'content/user/about-sharing-of-objects.md'
  - 'Data Administration': 'content/user/data-administration.md'
  - 'Datastore Manager': 'content/user/datastore-manager.md'
  - 'Configure GIS/Maps': 'content/user/configure-the-gis-app.md'
  - 'Configure Reports': 'content/user/configure-report-functionality.md'
  - 'Import/Export': 'content/user/importexport-app.md'
  - 'Metadata Synchronizing': 'content/user/configure-metadata-synchronizing.md'
  - 'Mobile': 'content/user/mobile.md'
  - 'Tutorials': 'content/user/dhis2-tutorials.md'
  - 'About DB Design': 'content/user/about-demo-server-live-package-and-database-design.md'
  - 'About Data Dimensions': 'content/user/about-data-dimensions.md'
  - 'Additional Data Dimensions': 'content/user/additional-data-dimensions.md'
  - 'FAQ': 'content/user/dhis2-frequently-asked-questions.md'
  - 'Release and Upgrade Notes': 'content/user/release-and-upgrade-notes.md'
  - 'User Authorities': 'content/user/user-authorities.md'
  - 'Sytem Settings': 'content/user/system-settings.md'
  - 'Glossary': 'content/user/dhis2-glossary.md'
  
theme: readthedocs